# Model witch will be used for build visual embeddings
# Possible values: "resnet18", "resnet34", "resnet50", "resnet101", "resnet152", "efficientnet_b0",
# "efficientnet_b1", "efficientnet_b2", "efficientnet_b3", "efficientnet_b4", "efficientnet_b5",
# "efficientnet_b6", "efficientnet_b7"
model: "resnet50"